### ISSUE TITLE
Installation as described in README.md fails

### ISSUE THREAD

**Issue by TNSaturday** [JohnWall2016/fullstack-vue-code#1]
I'm on Windows 10 x64, my node version is 12.13.0, npm 6.12.0, I run the instructions in your README and get:
```bash
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'install-all'
1 verbose cli ]
2 info using npm@6.12.0
3 info using node@v12.13.0
4 verbose run-script [ 'preinstall-all', 'install-all', 'postinstall-all' ]
5 info lifecycle fullstack-vue-code@17.0.0~preinstall-all: fullstack-vue-code@17.0.0
6 info lifecycle fullstack-vue-code@17.0.0~install-all: fullstack-vue-code@17.0.0
7 verbose lifecycle fullstack-vue-code@17.0.0~install-all: unsafe-perm in lifecycle true
8 verbose lifecycle fullstack-vue-code@17.0.0~install-all: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\dev\fullstack-vue-code\node_modules\.bin;C:\cmder\bin;C:\cmder\vendor\bin;C:\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\cmder\vendor\conemu-maximus5;C:\cmder\vendor\conemu-maximus5\ConEmu;C:\Python27\;C:\Python27\Scripts;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\cmder\vendor\git-for-windows\bin;C:\Program Files (x86)\Google\Chrome\Application;C:\Users\TSubbota\AppData\Local\Microsoft\WindowsApps;C:\Users\TSubbota\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\TSubbota\AppData\Roaming\npm;C:\cmder\vendor\git-for-windows\cmd;C:\cmder\vendor\git-for-windows\mingw64\bin;C:\cmder\vendor\git-for-windows\usr\bin;C:\cmder
9 verbose lifecycle fullstack-vue-code@17.0.0~install-all: CWD: C:\dev\fullstack-vue-code
10 silly lifecycle fullstack-vue-code@17.0.0~install-all: Args: [ '/d /s /c', 'npm-recursive-install' ]
11 silly lifecycle fullstack-vue-code@17.0.0~install-all: Returned: code: 1  signal: null
12 info lifecycle fullstack-vue-code@17.0.0~install-all: Failed to exec install-all script
13 verbose stack Error: fullstack-vue-code@17.0.0 install-all: `npm-recursive-install`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid fullstack-vue-code@17.0.0
15 verbose cwd C:\dev\fullstack-vue-code
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "install-all"
18 verbose node v12.13.0
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 1
22 error fullstack-vue-code@17.0.0 install-all: `npm-recursive-install`
22 error Exit status 1
23 error Failed at the fullstack-vue-code@17.0.0 install-all script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Have you tried yourself? Please, update your instructions or give some info on how to make it work.

**Comment by TNSaturday** [comment]
Installing dependencies for calendar app solely gives:

```bash
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\dev\fullstack-vue-code\calendar_app\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\dev\\fullstack-vue-code\\calendar_app\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\dev\fullstack-vue-code\calendar_app\node_modules\node-sass
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by torressam333** [comment]
@TNSaturday did you ever resolve this? I have this issue right now using node 16.13.0 and npm 7.24.2. Can't install dep's out of the box for this repo.

**Comment by TNSaturday** [comment]
> @TNSaturday did you ever resolve this? I have this issue right now using node 16.13.0 and npm 7.24.2. Can't install dep's out of the box for this repo.

Yes, I did. You should get a new version of the code at the publisher's website. If works fine
